### ISSUE TITLE
Cannot resolve scoped service 'Digipolis.ServiceAgents.IRequestHeaderHelper' from root provider.

### ISSUE THREAD

**Issue by woeterman94** [digipolisantwerp/serviceagents_aspnetcore#27]
When using the service agent in a controller I get the following error:

`System.InvalidOperationException: Cannot resolve scoped service 'Digipolis.ServiceAgents.IRequestHeaderHelper' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Digipolis.ServiceAgents.HttpClientFactory.CreateClient(ServiceSettings settings) in c:\github\digipolisantwerp\serviceagents_aspnetcore\src\Digipolis.ServiceAgents\HttpClientFactory.cs:line 21
   at Digipolis.ServiceAgents.AgentBase.get__client() in c:\github\digipolisantwerp\serviceagents_aspnetcore\src\Digipolis.ServiceAgents\AgentBase.cs:line 35
   at Digipolis.Aanvragers.Proxy.ServiceAgents.AuthenticationServiceAgent.GetProfileByAccessTokenAsync(String accessToken) in C:\Users\ex02742\Documents\Code\_IOD\aanvragers-proxy_api_aspnetcore\Digipolis.Aanvragers.Proxy\ServiceAgents\AuthenticationServiceAgent.cs:line 65
   at Digipolis.Aanvragers.Proxy.Api.Controllers.AuthenticationController.getProfile() in C:\Users\ex02742\Documents\Code\_IOD\aanvragers-proxy_api_aspnetcore\Digipolis.Aanvragers.Proxy\Api\Controllers\AuthenticationController.cs:line 69
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()`

**Comment by Stephan-Ghequiere** [comment]
Looks like an old version. Ty updating to the newest version...
